# Generated by Django 2.2.7 on 2020-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0010_auto_20200224_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.IntegerField(db_column='referral_code', unique=True)),
                ('referral_name', models.CharField(db_column='referral_name', max_length=100)),
            ],
        ),
    ]
