# Generated by Django 2.2.7 on 2020-03-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0012_auto_20200302_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='CYF_code',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'CYF'), (2, 'Juvenile Justice')], db_column='CYF_code'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='ls_type',
            field=models.IntegerField(choices=[(1, 'voluntary'), (2, 'Dependent'), (5, 'Delinquent')], db_column='LS_Type'),
        ),
    ]
